
import { NETWORKS } from '@/lib/constants';
import { Network, SuiRpcResponse, BuilderArg } from '../types';
import { MOCK_OBJECTS } from './mockService';

const MOCK_BALANCE = '14500000000'; // 14.5 SUI

export const executeSuiRpc = async (
  network: Network,
  method: string,
  params: any[]
): Promise<{ result: any; duration: number; status: number }> => {
  const url = NETWORKS[network];
  const startTime = performance.now();
  
  // --- MOCK INTERCEPTION ---
  // Helper to return mock data if network fails or for demo purposes
  const mockFallback = async () => {
      await new Promise(r => setTimeout(r, 600 + Math.random() * 400)); // Fake latency
      const duration = Math.round(performance.now() - startTime);
      
      if (method === 'suix_getOwnedObjects') {
          return {
              result: { data: MOCK_OBJECTS },
              duration,
              status: 200
          };
      }
      if (method === 'suix_getBalance') {
          return {
              result: { totalBalance: MOCK_BALANCE },
              duration,
              status: 200
          };
      }
      if (method === 'sui_devInspectTransactionBlock') {
          return {
              result: {
                  effects: {
                      status: { status: 'success' },
                      gasUsed: { computationCost: '1000', storageCost: '500', storageRebate: '100', nonRefundableStorageFee: '0' },
                      executedEpoch: '420'
                  },
                  events: []
              },
              duration,
              status: 200
          };
      }
      
      // Default generic success for other RPC calls
      return {
          result: { 
              status: 'success', 
              note: 'Mock response generated by Flow Pro', 
              method, 
              timestamp: Date.now() 
          },
          duration,
          status: 200
      };
  };

  try {
    // Attempt real fetch with a short timeout to prefer mock data if network is unresponsive
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 2000); 
    
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        jsonrpc: '2.0',
        id: 1,
        method,
        params,
      }),
      signal: controller.signal
    });
    clearTimeout(timeoutId);

    const data: SuiRpcResponse = await response.json();
    const endTime = performance.now();
    const duration = Math.round(endTime - startTime);

    if (data.error) {
      console.warn("RPC Error (falling back to mock):", data.error);
      return mockFallback();
    }

    return {
      result: data.result,
      duration,
      status: response.status,
    };
  } catch (error: any) {
    // Network error or timeout -> use mock data
    return mockFallback();
  }
};

export const simulateMoveCall = async (
  network: Network,
  sender: string,
  packageId: string,
  module: string,
  func: string,
  typeArgs: string[],
  args: BuilderArg[]
) => {
    // Convert BuilderArgs to raw arguments for simulation/inspection
    // For simulation, we can often pass pure values as is, and object IDs as strings
    const rawArgs = args.map(arg => {
        if (arg.type === 'u64' || arg.type === 'u128' || arg.type === 'u256') {
            return arg.value; // Passed as string to avoid precision loss
        }
        if (arg.type === 'u8' || arg.type === 'u16' || arg.type === 'u32') {
            return parseInt(arg.value);
        }
        if (arg.type === 'bool') {
            return arg.value === 'true';
        }
        // Address, String, Object ID, etc.
        return arg.value;
    });

    const method = 'sui_devInspectTransactionBlock';
    const params = [
        sender,
        {
            kind: 'moveCall',
            target: `${packageId}::${module}::${func}`,
            typeArguments: typeArgs,
            arguments: rawArgs
        },
        null, 
        null
    ];
    
    return executeSuiRpc(network, method, params);
};

export const getOwnedObjects = async (network: Network, address: string) => {
    return executeSuiRpc(network, 'suix_getOwnedObjects', [
        address,
        { options: { showType: true, showContent: true, showDisplay: true } }
    ]);
};

export const getObject = async (network: Network, objectId: string) => {
    return executeSuiRpc(network, 'sui_getObject', [
        objectId,
        { showType: true, showContent: true, showOwner: true }
    ]);
};

export const getBalance = async (network: Network, owner: string) => {
    return executeSuiRpc(network, 'suix_getBalance', [
        owner,
        '0x2::sui::SUI'
    ]);
};
